[phases.setup]
nixPkgs = ['...', 'php82', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring', 'php82Extensions.tokenizer', 'php82Extensions.xml', 'php82Extensions.ctype', 'php82Extensions.json', 'php82Extensions.bcmath', 'php82Extensions.openssl']

[phases.install]
cmds = [
    'composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction --no-progress'
]

[phases.build]
cmds = [
    'chmod +x start.sh',
    'mkdir -p storage/framework/cache/data',
    'mkdir -p storage/framework/views',
    'mkdir -p storage/framework/sessions',
    'mkdir -p storage/logs',
    'mkdir -p bootstrap/cache',
    'chmod -R 775 storage',
    'chmod -R 775 bootstrap/cache'
]

[start]
cmd = 'bash start.sh'
